source 'https://rubygems.org'

gem "cucumber", "1.3.6"
gem "selenium-webdriver", "2.39.0"
gem "capybara", "2.1.0"
gem "poltergeist", "1.4.1"
gem "sauce", "3.2.0"
gem "json", "1.7.6"
gem "parallel_tests"
gem "sauce-cucumber", "~> 3.2.1"
gem "rspec"
gem "activesupport", "~> 4.0.2"
gem "rake"
gem "guard-cucumber"
gem "yard-cucumber"
gem "random-word"
gem "faker"
gem "simple-password-gen"
gem "mailosaur"
gem "awesome_print", "~> 1.2.0"
gem "imgkit"
